# Dockerfile

FROM python:3.11-slim

# Set working directory inside the container
WORKDIR /app

# Set PYTHONPATH to allow absolute imports from /app
ENV PYTHONPATH=/app

# Install dependencies
COPY fastapi/requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

# Copy everything under fastapi into /app
COPY fastapi /app

# Run FastAPI app
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
