# services/data-aggregator/Dockerfile.dev
FROM base-python-dev
WORKDIR /app

COPY services/data-aggregator /app
COPY libs /app/libs
RUN python -c "import libs.kafka_utils"

CMD ["sh", "-c", "uvicorn main:app --host 0.0.0.0 --port ${DATA_AGGREGATOR_PORT:-8003} --reload"]

