sequenceDiagram
    participant OS as OpenSneseMap
    participant DC as Data Ingestor
    participant KK as Kafka
    participant EL as Data Processor
    participant DB as MongoDB
    participant GN as Grafana

    DC->>OS: Fetch IoT Data
    activate OS
    activate DC
    OS-->>DC: Return IoT Data
    deactivate OS
    DC->>DC: Validata Data
    DC->>KK: Publish IoT Data as Kafka Topic
    deactivate DC
    EL->>KK: Poll IoT Data Event
    activate EL
    EL->>EL: Trasform Data
    EL->>DB: Store Structured Data
    deactivate EL
    GN->>DB: Retrieve Structured Data

