flowchart TD
    OS(OpenSnese)
    DC(Data Collector)
    KK@{shape: das, label: "Kafka"}
    EL(Event Listener)
    DB[(MongoDB)]
    GN(Grafana)

    DC-->|Fetch via API|OS
    DC-->|Publish Kafka Topic|KK
    EL-->|Consume Kafka Topic|KK
    EL-->|Store Sensor Data|DB
    GN-->|Fetch Sensor Data|DB