FROM python:3.10-slim

# Set working directory
WORKDIR /app

# Install dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Add the shared libs folder
COPY ../../libs ./libs

# Add PYTHONPATH for module resolution
ENV PYTHONPATH=/app

# Run the service
CMD ["python", "./main.py"]
