# services/schema-inspector/Dockerfile.dev
FROM base-python-dev
WORKDIR /app

COPY services/schema-inspector /app
COPY libs /app/libs
RUN python -c "import libs.kafka_utils"
ENV PORT=${SCHEMA_INSPECTOR_PORT}
CMD uvicorn main:app --host 0.0.0.0 --port ${SCHEMA_INSPECTOR_PORT:-8004} --reload





