FROM base-python-dev

WORKDIR /app
COPY . /app

# Optional sanity check to debug inside container
RUN python -c "import jsonschema"

CMD ["sh", "-c", "uvicorn main:app --host 0.0.0.0 --port $PORT --reload"]