# services/data-processor/Dockerfile.dev
FROM base-python-dev
WORKDIR /app

COPY services/data-processor /app
COPY libs /app/libs
RUN python -c "import libs.kafka_utils"
ENV PORT=${DATA_PROCESSOR_PORT}
CMD uvicorn main:app --host 0.0.0.0 --port ${DATA_PROCESSOR_PORT:-8002} --reload

